
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author NguyenKhanh
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/image/icon.png"));
        setIconImage(icon);
        setSize(1350, 650);
        setResizable(false);//lock size
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        lbInfor.setVisible(false);
        lbInfor1.setVisible(false);
        lbInfor2.setVisible(false);
        lbInfor3.setVisible(false);
        lbInHelp.setVisible(false);
        lbHelp_infor1.setVisible(false);
        lbHelp_infor2.setVisible(false);
        lbHelp_infor3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCLOSE = new javax.swing.JLabel();
        lbHelp_infor3 = new javax.swing.JLabel();
        lbHelp_infor2 = new javax.swing.JLabel();
        lbHelp_infor1 = new javax.swing.JLabel();
        lbInHelp = new javax.swing.JLabel();
        lbInfor = new javax.swing.JLabel();
        lbInfor1 = new javax.swing.JLabel();
        lbInfor2 = new javax.swing.JLabel();
        lbInfor3 = new javax.swing.JLabel();
        lbInforGroup = new javax.swing.JLabel();
        lbHELP = new javax.swing.JLabel();
        lbNameGame = new javax.swing.JLabel();
        lbBackground = new javax.swing.JLabel();
        lbhelp2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Game");
        getContentPane().setLayout(null);

        lbCLOSE.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lbCLOSE.setForeground(new java.awt.Color(255, 204, 0));
        lbCLOSE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCLOSE.setText("CLOSE");
        lbCLOSE.setToolTipText("Back againt menu");
        lbCLOSE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbCLOSE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCLOSEMouseClicked(evt);
            }
        });
        getContentPane().add(lbCLOSE);
        lbCLOSE.setBounds(590, 540, 90, 70);

        lbHelp_infor3.setBackground(new java.awt.Color(255, 255, 255));
        lbHelp_infor3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbHelp_infor3.setForeground(new java.awt.Color(255, 255, 255));
        lbHelp_infor3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHelp_infor3.setText("If you don't meet your goal by the end of time  it's game over");
        lbHelp_infor3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbHelp_infor3MouseClicked(evt);
            }
        });
        getContentPane().add(lbHelp_infor3);
        lbHelp_infor3.setBounds(30, 340, 1350, 70);

        lbHelp_infor2.setBackground(new java.awt.Color(255, 255, 255));
        lbHelp_infor2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbHelp_infor2.setForeground(new java.awt.Color(255, 255, 255));
        lbHelp_infor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHelp_infor2.setText("Once is has grabbed something it will reel it up.Collect the target amount is 1000 score your . If you have 1000 score you can next to level ");
        lbHelp_infor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbHelp_infor2MouseClicked(evt);
            }
        });
        getContentPane().add(lbHelp_infor2);
        lbHelp_infor2.setBounds(30, 270, 1350, 70);

        lbHelp_infor1.setBackground(new java.awt.Color(255, 255, 255));
        lbHelp_infor1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbHelp_infor1.setForeground(new java.awt.Color(255, 255, 255));
        lbHelp_infor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHelp_infor1.setText("Use your claw and reel to mine gold and other treasures out of the earth . Your claw will swing back and forth .Press the down arrow to lower it.");
        lbHelp_infor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbHelp_infor1MouseClicked(evt);
            }
        });
        getContentPane().add(lbHelp_infor1);
        lbHelp_infor1.setBounds(10, 210, 1350, 70);

        lbInHelp.setBackground(new java.awt.Color(255, 204, 0));
        lbInHelp.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lbInHelp.setForeground(new java.awt.Color(255, 153, 0));
        lbInHelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInHelp.setText("INSTRUCTIONS");
        lbInHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbInHelpMouseClicked(evt);
            }
        });
        getContentPane().add(lbInHelp);
        lbInHelp.setBounds(0, 110, 1320, 70);

        lbInfor.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lbInfor.setForeground(new java.awt.Color(51, 204, 0));
        lbInfor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInfor.setText("======GROUP PASS======");
        getContentPane().add(lbInfor);
        lbInfor.setBounds(430, 30, 510, 70);

        lbInfor1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lbInfor1.setForeground(new java.awt.Color(51, 255, 0));
        lbInfor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInfor1.setText("1.Nguyễn Đặng Quốc Khánh - CE130174");
        getContentPane().add(lbInfor1);
        lbInfor1.setBounds(440, 90, 540, 70);

        lbInfor2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lbInfor2.setForeground(new java.awt.Color(102, 255, 51));
        lbInfor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInfor2.setText("2.Nguyễn Duy Thanh - CE130015");
        getContentPane().add(lbInfor2);
        lbInfor2.setBounds(440, 140, 460, 70);

        lbInfor3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lbInfor3.setForeground(new java.awt.Color(102, 255, 0));
        lbInfor3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInfor3.setText("3.Lê Phúc Hậu - CE130176");
        getContentPane().add(lbInfor3);
        lbInfor3.setBounds(460, 190, 340, 70);

        lbInforGroup.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lbInforGroup.setForeground(new java.awt.Color(255, 204, 0));
        lbInforGroup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInforGroup.setText("INFORMATION");
        lbInforGroup.setToolTipText("Information of group");
        lbInforGroup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbInforGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbInforGroupMouseClicked(evt);
            }
        });
        getContentPane().add(lbInforGroup);
        lbInforGroup.setBounds(670, 450, 190, 70);

        lbHELP.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lbHELP.setForeground(new java.awt.Color(255, 204, 0));
        lbHELP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHELP.setText("HELP");
        lbHELP.setToolTipText("Help about instructions");
        lbHELP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbHELP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbHELPMouseClicked(evt);
            }
        });
        getContentPane().add(lbHELP);
        lbHELP.setBounds(490, 450, 90, 70);

        lbNameGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/namegame.png"))); // NOI18N
        getContentPane().add(lbNameGame);
        lbNameGame.setBounds(330, 0, 770, 420);

        lbBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background-sheet1.png"))); // NOI18N
        getContentPane().add(lbBackground);
        lbBackground.setBounds(0, 0, 1360, 650);

        lbhelp2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lbhelp2.setForeground(new java.awt.Color(51, 255, 0));
        lbhelp2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbhelp2.setText("1.Nguyễn Đặng Quốc Khánh - CE130174");
        getContentPane().add(lbhelp2);
        lbhelp2.setBounds(450, 90, 540, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbInforGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbInforGroupMouseClicked
        
        //show information of group
        lbInfor.setVisible(true);
        lbInfor1.setVisible(true);
        lbInfor2.setVisible(true);
        lbInfor3.setVisible(true);
        lbNameGame.setVisible(false);
        lbInHelp.setVisible(false);
        lbHelp_infor1.setVisible(false);
        lbHelp_infor2.setVisible(false);
        lbHelp_infor3.setVisible(false);
    }//GEN-LAST:event_lbInforGroupMouseClicked

    private void lbInHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbInHelpMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbInHelpMouseClicked

    private void lbHelp_infor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHelp_infor1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbHelp_infor1MouseClicked

    private void lbHelp_infor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHelp_infor2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbHelp_infor2MouseClicked

    private void lbHelp_infor3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHelp_infor3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbHelp_infor3MouseClicked

    private void lbHELPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHELPMouseClicked
        
        //show instruction of game
        lbInHelp.setVisible(true);
        lbHelp_infor1.setVisible(true);
        lbHelp_infor2.setVisible(true);
        lbHelp_infor3.setVisible(true);
        lbNameGame.setVisible(false);
        lbInfor.setVisible(false);
        lbInfor1.setVisible(false);
        lbInfor2.setVisible(false);
        lbInfor3.setVisible(false);
    }//GEN-LAST:event_lbHELPMouseClicked

    private void lbCLOSEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCLOSEMouseClicked
        
        //Close menu
        setVisible(false);
        
    }//GEN-LAST:event_lbCLOSEMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbCLOSE;
    private javax.swing.JLabel lbHELP;
    private javax.swing.JLabel lbHelp_infor1;
    private javax.swing.JLabel lbHelp_infor2;
    private javax.swing.JLabel lbHelp_infor3;
    private javax.swing.JLabel lbInHelp;
    private javax.swing.JLabel lbInfor;
    private javax.swing.JLabel lbInfor1;
    private javax.swing.JLabel lbInfor2;
    private javax.swing.JLabel lbInfor3;
    private javax.swing.JLabel lbInforGroup;
    private javax.swing.JLabel lbNameGame;
    private javax.swing.JLabel lbhelp2;
    // End of variables declaration//GEN-END:variables
}
